name: Tag Release
on:
  push:
    branches:
      - '**/release/**'
      - 'hotfix/**'
jobs:
  tagRelease:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: DevXP Branching Strategy - Setup
        uses: Flutter-Global/devxp-branching-strategy

      - name: Tag new version
        run: |
          git tag "$(bash ${GITHUB_WORKSPACE}/devxp-branching-strategy/gen-current-semver.sh)"
          git push origin --tags

      - name: Say Bye
        run: echo "Bye"
